/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#fefcff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#f8f9ff",
        "tertiary-fixed": "#62fae3",
        "secondary-container": "#1e293b",
        "on-primary-fixed-variant": "#004493",
        "surface-container-lowest": "#0b1221",
        "primary-container": "#0070ea",
        "surface-container": "#1e293b",
        "surface": "#020617",
        "primary-fixed-dim": "#adc7ff",
        "on-surface": "#f8f9ff",
        "background": "#020617",
        "inverse-primary": "#adc7ff",
        "secondary": "#94a3b8",
        "primary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005047",
        "inverse-on-surface": "#0b1c30",
        "on-surface-variant": "#cbd5e1",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#00201c",
        "surface-container-low": "#0f172a",
        "inverse-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "outline-variant": "#334155",
        "surface-bright": "#1e293b",
        "primary": "#3b82f6",
        "on-primary-fixed": "#001a41",
        "on-tertiary": "#ffffff",
        "surface-tint": "#005bc0",
        "surface-container-high": "#1e293b",
        "on-secondary-container": "#cbd5e1",
        "tertiary-container": "#008375",
        "surface-dim": "#020617",
        "outline": "#475569",
        "on-secondary-fixed": "#131b2e",
        "surface-variant": "#1e293b",
        "surface-container-highest": "#334155",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#3cddc7",
        "tertiary": "#00685c",
        "on-tertiary-container": "#f4fffb",
        "on-secondary-fixed-variant": "#3f465c",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "40px",
        "unit": "4px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "container-max": "1200px",
        "lg": "24px",
        "xxl": "64px",
        "gutter": "24px"
      },
      "fontFamily": {
        "h1": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "button": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "h3": ["Plus Jakarta Sans"],
        "h2": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "button": ["15px", {"lineHeight": "1", "letterSpacing": "0", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}

